### ISSUE TITLE
usage question

### ISSUE THREAD

**Issue by HaroldSP** [m-lundberg/simple-pid#20]
Hello everyone!

Is there any more detailed usage example?

Let's say, I have a car with a range sensor, which gives me the distance to the wall, and I have the desired distance, so according to an error I send different PWM values to motors.

How the code would look like?

Thanks.

**Comment by m-lundberg** [comment]
Hello!

There are a few examples in the [readme](https://github.com/m-lundberg/simple-pid/blob/master/README.md) and [a complete example application](https://github.com/m-lundberg/simple-pid/tree/master/examples/water_boiler). Is there something specific you don't understand from those examples?

You probably want to set the `output_limits` on your PID controller to `(0, 255)` or whatever the max PWM output is in your case.

**Comment by HaroldSP** [comment]
Thanks! 

The example helped.
