### ISSUE TITLE
Setting set point with in a range.[Question]

### ISSUE THREAD

**Issue by mmkumr** [m-lundberg/simple-pid#23]
How to can I set the setPoint variable with range of values. Example setting the setPoint values  between -1 to 3.

**Comment by m-lundberg** [comment]
Hi,

I'm not sure I understand what you mean by setting the setpoint to a range of values. The setpoint is the value that the PID is trying to achieve. If you want the PID to stop controlling when it is within a range of values you would need to do that with some logic outside of the PID itself.

**Comment by m-lundberg** [comment]
I'm closing this now, let me know if you have any further questions.
