### ISSUE TITLE
PID setpoint not in PID.pyi

### ISSUE THREAD

**Issue by jamesbraza** [m-lundberg/simple-pid#35]
The public attribute `setpoint` in `simple_pid.PID.PID` is not exposed in the `.pyi`.

When scanning with mypy, it throws an error:

```
error: "PID" has no attribute "setpoint"  [attr-defined]
```

A few ideas:
- Add `setpoint` to the `.pyi`
- Make `setpoint` private if it's not supposed to be public

---

Versions

```
Python==3.8.5
simple-pid==1.0.0
mypy==0.812
```

**Comment by m-lundberg** [comment]
I was not aware of this. Thanks for letting me know!

I have included `setpoint` and all the other public member variables in the typing stub and released it in version 1.0.1.
