### ISSUE TITLE
DC Servo Motor position control with an implemented Fuzzy-PID Controller using Raspberry Pi Pico

### ISSUE THREAD

**Issue by Nmsngym** [m-lundberg/simple-pid#47]
Hello! May I ask if you have any ideas on how to program/code a Fuzzy-PID Controller in Raspberry Pi Pico/Micropython?
I have a project on implementing a control system, Fuzzy-PID Controller, in my DC Servo Motor for the position control using RPi Pico. Well, my college department does not authorize the use of Arduino. :((
I saw your repositories and see it as a guide, tho, I'm still confused because mine is position control.
The model of my servo motor is DSS-M15S.

**Comment by m-lundberg** [comment]
Hi, like I mentioned in the PR you created I can't really help you with this.
