### ISSUE TITLE
mypy error simple_pid/PID.pyi:45: error: Name "output_limits" already defined on line 17 

### ISSUE THREAD

**Issue by rnestler** [m-lundberg/simple-pid#50]
It seems that `output_limits` is defined twice: Once on line 17 and then again on line 45 and 46.

**Comment by rnestler** [comment]
It would probably be good to run `mypy --strict simple_pid` during CI to avoid issues like this. Also since Python 2 is EOL you could consider removing Python 2 support and use inline type annotations, which are easier to manage.

**Comment by m-lundberg** [comment]
You are right, mypy should be run in CI to detect things like this. I will create an issue for this.
