### ISSUE TITLE
Rename PID module

### ISSUE THREAD

**Issue by m-lundberg** [m-lundberg/simple-pid#53]
As mentioned in #48, calling the module `PID.py` is not very appropriate. To follow pep 8 it should be called `pid.py` instead. Think about how breaking this change would be and possibly rename the module.

**Comment by rnestler** [comment]
> Think about how breaking this change would be and possibly rename the module.

I'm not sure if it is really breaking, since the module currently can't get imported since it is shadowed by the re-export of the PID class.
