### ISSUE TITLE
Package installed from pip and local one are different

### ISSUE THREAD

**Issue by datonefaridze** [m-lundberg/simple-pid#65]
Hello, Package installed from pip and local one are different, also package installed from pip has this issue:
```
self._derivative = -self.Kd * d_input / dt
```
why there is minus sign here?

**Comment by m-lundberg** [comment]
Hi. Can you please provide more details about how the package installed from pip is different from a local one? What are the steps to reproduce it, and how exactly are they different?

As for the minus sign, please see [here](http://brettbeauregard.com/blog/2011/04/improving-the-beginner%e2%80%99s-pid-derivative-kick/) for an explanation.
