### ISSUE TITLE
import issue

### ISSUE THREAD

**Issue by NLuca** [m-lundberg/simple-pid#89]
I can not import the library.
import simple-pid as PID --> "SyntaxError: invalid syntax"
If I use "_" instead of "-" I get:
ModuleNotFoundError: No module named 'simple_pid'
What do you recommend?
Thank you.

**Comment by m-lundberg** [comment]
As the error suggests, the module could not be found. Please double check that you installed the library correctly with pip.

**Comment by NLuca** [comment]
Hi Martin,

I am using PyCharm for my project. I have tried to install the module
through the PyCharm interface and also using the PyCharm terminal. I have
the same errors in both cases. What do you recommend?

Best regards,
Luca Neri

**Comment by NLuca** [comment]
Hi Martin,

I have just solved the problem by installing the module outside PyCharm.

Thank you.
Best regards,
Luca Neri
